language: android
sudo: false
jdk: oraclejdk7
env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20 # wait up to 20 minutes for adb to connect to emulator

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

  # Emulator for the tests
  - sys-img-armeabi-v7a-android-23

cache:
  directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_install:
  - chmod +x gradlew
  - pip install --user codecov

before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
  - rm /home/travis/.gradle/caches/2.8/plugin-resolution/cache.properties.lock
  
branches:
  only:
    - master
    - beta
    - alpha

after_success:
  - ./gradlew jacocoFullReport
  - codecov

after_failure:
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done
