language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script: "./gradlew clean assemble check generateReleaseJavadoc --info --stacktrace"
   
before_install:
 - chmod +x gradlew
